### ISSUE TITLE
Standardize testing strategy for React

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-guidelines#49] opened 2019-06-28 10:36 UTC
As the number of React projects grows, we need some common agreement on how to test those components and applications.

We already have some differing examples at:
- [master:segments-web](https://github.com/andresfulla/liferay-portal/tree/master/modules/apps/segments/segments-web/test/js)
- [master-private:portal-workflow-metrics-web](https://github.com/liferay/liferay-portal-ee/tree/master-private/modules/private/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/components/__tests__) (already not following our test folder convention which we should document, so I've created https://github.com/liferay/liferay-frontend-guidelines/issues/50 for it)
- [master-private: portal-search-ranking-web](https://github.com/arboliveira/liferay-portal/tree/LPS-89524_Search_Tuning_Result_Rankings/modules/apps/portal-search/portal-search-ranking-web/test/js). @thektan also started a request about [Add @testing-library/react and jest-dom](https://github.com/liferay/liferay-npm-tools/issues/108)

We should have some clear guidelines and common infra that we can recommend to make sure we have reliable and consistent tests across the product.

**Comment by jbalsas** [comment] 2019-06-28 10:48
Invoking interested parties @bryceosterhaus, @matuzalemsteles, @wincent, @thektan, @andresfulla, @brunobasto, @phcp, @p2kmgcl... feel free to ping anyone else that might have some input.

**Comment by bryceosterhaus** [comment] 2019-06-28 15:24
Few thoughts from my experience with jest and testing react:

- I think using `react-testing-library`(now @testing-library/react) has made me write better and more useful tests.
- Testing user functionality rather than implementation details. Refactors won't break tests.
- Don't rely on snapshots too much. Its nice to have a few general snapshots of how a component renders, but generally I have found that the more snapshots you have, the less helpful they are.
- Prefer explicit `.toBe(...)` values rather than snapshots.
- Personally I prefer using fakeTimers and `runAllTimers` rather than async tests. Granted, this probably depends on situation.

I think one of my biggest take aways was testing user functionality over implementation details. This means I would rather test how a user would interact with a specific feature rather than testing the return of some callback. This has been the most useful way to write tests for me.

**Comment by john-co** [comment] 2019-07-02 21:13
I wanted to also echo avoiding snapshots as much as possible since they end up being a time sink to update the test and basing quality of the component on these kinds of tests brings a false sense of security. Most of the jest failures that I reviewed on CI are caused by snapshots not being updated. So having less snapshots will save time on unnecessary maintenance in my opinion.

Doing a google search on jest snapshot brings this up as a top hit: https://medium.com/@tomgold_48918/why-i-stopped-using-snapshot-testing-with-jest-3279fe41ffb2

The link points to another article that provides how to best test react components: https://itnext.io/how-to-properly-test-react-components-9f090969cb6f which discusses the concept @bryceosterhaus had already pointed out testing functionality over implementation.

**Comment by matuzalemsteles** [comment] 2019-07-03 13:47
I would say the same thing as Bryce, we used many snapshot tests when we were creating Clay in its first version with Metal components, we could have other approaches but it was the fastest to write but a lot of snapshots could cause problems , since you can run `jest -u` and update all, a lot can go unnoticed and it can still be bad to review all the changes in a review.

So using `@testing-library/react` is helping us to create better tests oriented to user interactions... this gives us more security but even so we still have some snapshot tests for only markup verification.

It has also enzyme but I did not use it so much, @oliveiraaraujo can say more about it than me.

**Comment by wincent** [comment] 2019-07-11 07:10
For reference, this is the internal ticket that corresponds to this discussion that I'm working on right now: https://issues.liferay.com/browse/LPS-97586

**Comment by andresfulla** [comment] 2019-07-11 12:10
I found `@testing-library/user-event` pretty useful too. It allows to type in tests as easy as `userEvent.type(inputElement, 'some text')`. More: https://github.com/testing-library/user-event

Also, `data-testid`, it sounds bad, but it makes testing a lot easier. I've been trying to avoid it lately and it feels jQueryish, and tests are more fragile. Perhaps we could get rid of it on `production` builds and leave it there for `developement`?

**Comment by matuzalemsteles** [comment] 2019-07-11 13:04
hey @andresfulla, we have this in Clay, we removed the `data-testid` for production, we use only in development environment. https://github.com/liferay/clay/blob/master/babel.config.js#L11-L22

**Comment by wincent** [comment] 2019-07-11 13:22
Specifically about `data-testid`, that one is a bit more controversial and @jbalsas will be able to comment on that. My understanding is that in the past we've had objections to test and implementation having divergent behavior.

> I've been trying to avoid it lately and it feels jQueryish, and tests are more fragile.

I'd say avoiding it is the right call, especially in liferay-portal, until we discuss the pros and cons. If it's not `data-testid`, there might be some other approach we can find that delivers the same kind of ergonomics without raising any concerns.

**Comment by brunofarache** [comment] 2019-07-12 21:12
added some comments to: https://github.com/jbalsas/liferay-portal/pull/1819

**Comment by wincent** [comment] 2019-07-15 12:49
I sent the first steps towards this upstream here: https://github.com/brianchandotcom/liferay-portal/pull/75708

Please continue to add suggestions or comments to this issue so that we can continue refining the approach and making useful things available in a standard way across liferay-portal.

**Comment by wincent** [comment] 2019-07-16 08:28
Trying to codify some of this in a document: https://github.com/liferay/liferay-frontend-guidelines/pull/62

**Comment by wincent** [comment] 2020-12-18 16:38
GitHub seems to have dropped the transfer job on the floor 😢

Most of the comments did not make it over to the transferred issue (https://github.com/liferay/liferay-frontend-projects/issues/351).

Oh well, going to close this anyway because I want to clean this whole repo of issues before requesting that it be archived.

**Closed by wincent** 2020-12-18 16:38 UTC
